services:
  - type: web
    name: defi-security-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: 'gunicorn src.app:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT'
    envVars:
      - key: ETHEREUM_RPC_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health
    autoDeploy: true
