services:
  - type: web
    name: defi-security-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ETHEREUM_RPC_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health
    autoDeploy: true
